In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("Everything is working!")

Pandas version: 2.3.3
Everything is working!

In [8]:
import os

folder = r"D:\MScProjects\labour-market-intelligence\data\raw\ons"

print(os.path.exists(folder))
print(os.listdir(folder))

True
['ONS_ASHE_Local_Authority.zip', 'ONS_ASHE_Occupation_2023', 'ONS_ASHE_Occupation_2024', 'ONS_ASHE_Occupation_2025', 'ONS_ASHE_Region_Occupation_2023', 'ONS_ASHE_Region_Occupation_2024', 'ONS_ASHE_Region_Occupation_2025', 'ONS_Online_Job_Advert_Salaries_2017_2025.xlsx.xlsx', 'ONS_Textkernel_Job_Adverts.xlsx.xlsx']

In [1]:
import sys
print(sys.executable)

d:\MScProjects\labour-market-intelligence\.venv\Scripts\python.exe

In [2]:
import pandas as pd

file_path = r"D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_Textkernel_Job_Adverts.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['Cover',
 'Contents',
 'Notes',
 '1.Region NSA',
 '2.Occupation 2-Digit NSA',
 '3.Occupation 4-Digit NSA']

In [ ]:
region_raw = pd.read_excel(file_path, sheet_name="1.Region NSA", header=None)

region_raw.head(15)
# pd.read_excel() → reads Excel data into a Pandas DataFrame.
# sheet_name= → chooses the worksheet.
# header=None → tells Pandas not to treat any row as column headings yet.
# region_raw → stores the result.
# Why? You are first inspecting the raw structure of the sheet.

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"Table 1: New online job adverts in the UK, spl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains one table. See Notes w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Back to Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Back to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Month,Total UK,East Midlands,East of England,London,North East,North West,South East,South West,West Midlands,Yorkshire and The Humber,England,Scotland,Wales,Northern Ireland,Unknown
5,2018-01-01 00:00:00,993156,51439,77949,225254,21161,83946,136388,74141,84350,57724,812337,36798,21102,14023,108896
6,2018-02-01 00:00:00,854140,43551,65483,199366,17357,70362,112140,61411,67446,49907,687010,33639,18109,11204,104178
7,2018-03-01 00:00:00,921648,46442,71240,211038,18924,77620,124705,68365,73818,54301,746437,36615,19507,12138,106951
8,2018-04-01 00:00:00,819751,42730,65726,183039,16650,67467,112642,60435,69484,48608,666771,32915,17434,10457,92174
9,2018-05-01 00:00:00,891434,48579,72531,200912,18147,76771,126511,67709,80669,54338,746152,38026,17315,12405,77536
10,2018-06-01 00:00:00,929598,50981,75824,207563,20479,80920,133831,71838,82899,57205,781526,40889,19797,12318,75068
11,2018-07-01 00:00:00,871470,46770,72281,200363,18566,75357,123054,68085,78553,52242,735257,37802,18548,10903,68960
12,2018-08-01 00:00:00,851109,46685,65175,203495,17608,74450,115429,65526,70204,51402,709959,39054,18545,11239,72312
13,2018-09-01 00:00:00,925258,51520,70308,204587,19613,78622,126209,70147,74909,55728,751623,42977,20033,13140,97485
14,2018-10-01 00:00:00,918490,50545,69471,202632,19441,80238,126206,71655,76402,56094,752671,41874,19734,12535,91676

In [4]:
occupation_raw = pd.read_excel(
    file_path,
    sheet_name="3.Occupation 4-Digit NSA",
    header=None
)

occupation_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,405,406,407,408,409,410,411,412,413,414
0,"Table 3: New online job adverts in the UK, spl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains one table. See Notes w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Back to Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Back to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Month,All Occupations,1111 Chief executives and senior officials,1112 Elected officers and representatives,1121 Production managers and directors in manu...,1122 Production managers and directors in cons...,1123 Production managers and directors in mini...,1131 Financial managers and directors,"1132 Marketing, sales and advertising directors",1133 Public relations and communications direc...,...,9259 Elementary storage occupations n.e.c.,9261 Bar and catering supervisors,9262 Hospital porters,9263 Kitchen and catering assistants,9264 Waiters and waitresses,9265 Bar staff,9266 Coffee shop workers,9267 Leisure and theme park attendants,9269 Other elementary services occupations n.e.c.,Unknown
5,2018-01-01 00:00:00,993156,944,643,5355,3893,151,9622,3887,475,...,703,1559,79,9633,3096,2867,635,1389,828,1248
6,2018-02-01 00:00:00,854140,811,504,4420,3080,259,8053,3242,386,...,654,1293,59,11202,2847,2775,420,1516,880,1090
7,2018-03-01 00:00:00,921648,732,632,5121,3715,173,8532,3807,435,...,701,1571,65,12407,3253,3246,497,1463,930,1041
8,2018-04-01 00:00:00,819751,651,630,4355,3014,242,7502,2993,388,...,618,1333,48,8773,2851,2885,463,2139,748,1007
9,2018-05-01 00:00:00,891434,679,1330,4570,3552,151,8155,3327,393,...,611,1495,52,9488,2934,2749,417,1768,724,1168
10,2018-06-01 00:00:00,929598,820,1593,4715,3257,356,7845,3443,376,...,778,1716,65,10166,3109,3087,491,1274,901,1160
11,2018-07-01 00:00:00,871470,711,1193,4857,3142,102,7560,3227,368,...,686,1504,41,10402,2786,3050,518,2199,863,1213
12,2018-08-01 00:00:00,851109,737,1375,4782,3193,142,7022,3091,353,...,768,1427,43,11828,2957,3111,688,1881,804,1675
13,2018-09-01 00:00:00,925258,791,696,5278,3389,128,7200,3183,342,...,792,1686,54,12810,3953,3762,884,2497,883,1963
14,2018-10-01 00:00:00,918490,786,717,5103,3329,140,7433,3212,409,...,673,1686,44,12429,3968,3903,815,2058,953,1960

In [5]:
# Get the occupation names from row 4
occupation_names = occupation_raw.iloc[4].dropna().astype(str)

# Search for occupations potentially relevant to our project
keywords = [
    "data",
    "information technology",
    "IT ",
    "software",
    "computer",
    "cyber",
    "security",
    "statistic",
    "technology"
]

matches = occupation_names[
    occupation_names.str.contains(
        "|".join(keywords),
        case=False,
        regex=True
    )
]

for occupation in matches:
    print(occupation)

1137 Information technology directors
2131 IT project managers
2132 IT managers
2133 IT business analysts, architects and systems designers
2134 Programmers and software development professionals
2135 Cyber security professionals
2136 IT quality and testing professionals
2137 IT network professionals
2139 Information technology professionals n.e.c.
2433 Actuaries, economists and statisticians
3131 IT operations technicians
3132 IT user support technicians
3133 Database administrators and web content technicians
3544 Data analysts
3573 Information technology trainers
4121 Credit controllers
4152 Data entry administrators
5244 Computer system and equipment installers and servicers
5245 Security system installers and repairers
7121 Collector salespersons and credit agents
9231 Security guards and related occupations

In [6]:
# Read the sheet correctly using row 4 as the header
occupation_df = pd.read_excel(
    file_path,
    sheet_name="3.Occupation 4-Digit NSA",
    header=4
)

# Convert Month to date
occupation_df["Month"] = pd.to_datetime(occupation_df["Month"])

# Keep data from 2023 onwards
occupation_2023 = occupation_df[
    occupation_df["Month"] >= "2023-01-01"
].copy()

# Select occupations relevant to our research
selected_columns = [
    "Month",
    "2134 Programmers and software development professionals",
    "2135 Cyber security professionals",
    "2433 Actuaries, economists and statisticians",
    "3133 Database administrators and web content technicians",
    "3544 Data analysts"
]

digital_demand = occupation_2023[selected_columns]

digital_demand.head()

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
60,2023-01-01,25269,3712,3993,2397,3606
61,2023-02-01,25118,3367,3131,2084,3358
62,2023-03-01,21905,3073,2908,1883,3261
63,2023-04-01,15409,2511,2473,1507,2462
64,2023-05-01,17787,2923,3069,1958,2962

In [7]:
digital_demand.tail()

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
97,2026-02-01,6619,1517,1338,1016,1321
98,2026-03-01,[x],[x],[x],[x],[x]
99,2026-04-01,7249,1639,1587,996,1334
100,2026-05-01,10232,2016,2015,1102,1505
101,2026-06-01,14641,2379,1990,1062,1798

In [8]:
print(digital_demand.shape)
print(digital_demand["Month"].min())
print(digital_demand["Month"].max())

(42, 6)
2023-01-01 00:00:00
2026-06-01 00:00:00

In [9]:
# Check missing values
digital_demand.isnull().sum()

Month                                                       0
2134 Programmers and software development professionals     0
2135 Cyber security professionals                           0
2433 Actuaries, economists and statisticians                0
3133 Database administrators and web content technicians    0
3544 Data analysts                                          0
dtype: int64

In [10]:
# Check data types
digital_demand.dtypes

Month                                                       datetime64[us]
2134 Programmers and software development professionals             object
2135 Cyber security professionals                                   object
2433 Actuaries, economists and statisticians                        object
3133 Database administrators and web content technicians            object
3544 Data analysts                                                  object
dtype: object

In [11]:
# Basic statistics
digital_demand.describe()

                            Month
count                          42
mean   2024-09-15 09:42:51.428571
min           2023-01-01 00:00:00
25%           2023-11-08 12:00:00
50%           2024-09-16 00:00:00
75%           2025-07-24 06:00:00
max           2026-06-01 00:00:00

In [12]:
# Check for duplicate months
digital_demand["Month"].duplicated().sum()

np.int64(0)

In [13]:
for col in digital_demand.columns[1:]:
    print("\n", col)
    print(digital_demand[col].unique()[:20])

 2134 Programmers and software development professionals
[25269 25118 21905 15409 17787 18059 14683 14362 10130 10885 10015 10583
 12467 9540 8820 9168 9123 7780 8404 7352]

 2135 Cyber security professionals
[3712 3367 3073 2511 2923 2889 2196 2268 1511 1689 1639 1715 1990 1461
 1442 1449 1524 1341 1637 1407]

 2433 Actuaries, economists and statisticians
[3993 3131 2908 2473 3069 2858 1888 1760 1719 1845 1899 1854 2061 1763
 1815 1757 1785 1457 1370 1234]

 3133 Database administrators and web content technicians
[2397 2084 1883 1507 1958 2069 1475 1435 1052 1176 1090 981 1440 1179 1101
 1185 1237 1100 1172 1058]

 3544 Data analysts
[3606 3358 3261 2462 2962 2965 2289 2084 1614 1741 1699 1558 1952 1643
 1457 1538 1664 1444 1566 1449]

In [14]:
# Convert occupation columns to numeric
for col in digital_demand.columns[1:]:
    digital_demand[col] = pd.to_numeric(
        digital_demand[col],
        errors="coerce"
    )

# Check data types again
digital_demand.dtypes

Month                                                       datetime64[us]
2134 Programmers and software development professionals            float64
2135 Cyber security professionals                                  float64
2433 Actuaries, economists and statisticians                       float64
3133 Database administrators and web content technicians           float64
3544 Data analysts                                                 float64
dtype: object

In [15]:
digital_demand.isnull().sum()

Month                                                       0
2134 Programmers and software development professionals     1
2135 Cyber security professionals                           3
2433 Actuaries, economists and statisticians                1
3133 Database administrators and web content technicians    1
3544 Data analysts                                          1
dtype: int64

In [16]:
digital_demand.describe()

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
count,42,41.000000,39.000000,41.000000,41.000000,41.000000
mean,2024-09-15 09:42:51.428571,11103.707317,1916.230769,1926.658537,1272.048780,1820.097561
min,2023-01-01 00:00:00,4754.000000,1032.000000,950.000000,598.000000,808.000000
25%,2023-11-08 12:00:00,7780.000000,1455.000000,1587.000000,1062.000000,1449.000000
50%,2024-09-16 00:00:00,9700.000000,1710.000000,1815.000000,1179.000000,1664.000000
75%,2025-07-24 06:00:00,12592.000000,2232.000000,2061.000000,1410.000000,2005.000000
max,2026-06-01 00:00:00,25269.000000,3712.000000,3993.000000,2397.000000,3606.000000
std,NaN,4813.433454,637.565702,602.779960,367.059665,625.893713

In [17]:
# Show rows where at least one selected occupation has a missing value
missing_rows = digital_demand[
    digital_demand.iloc[:, 1:].isna().any(axis=1)
]

missing_rows

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
89,2025-06-01,12215.0,NaN,2368.0,1410.0,2094.0
90,2025-07-01,9892.0,NaN,1750.0,1277.0,1757.0
98,2026-03-01,NaN,NaN,NaN,NaN,NaN

In [18]:
# Re-read original data without converting occupation columns
original_df = pd.read_excel(
    file_path,
    sheet_name="3.Occupation 4-Digit NSA",
    header=4
)

original_df["Month"] = pd.to_datetime(original_df["Month"])

original_selected = original_df[
    original_df["Month"].isin(missing_rows["Month"])
][selected_columns]

original_selected

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
89,2025-06-01,12215,[x],2368,1410,2094
90,2025-07-01,9892,[x],1750,1277,1757
98,2026-03-01,[x],[x],[x],[x],[x]

In [19]:
notes = pd.read_excel(
    file_path,
    sheet_name="Notes",
    header=None
)

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

notes

,0,1,2
0,Notes,NaN,NaN
1,This worksheet contains one table.,NaN,NaN
2,Note number,Note text,Applies to
3,1,"Some shorthand is used in this workbook, [x] = Data are unavailable.",All tables
4,2,"Textkernel has updated their methodologies and taxonomies throughout the timeseries back to 2017. This results in changes to classification of locations, which can produce some step-changes in the data.",All tables
5,3,"Users should be aware that we have noticed a large drop in new adverts in June 2025. This drop occurs in the underlying data received, as a large source has dropped off the deliveries. We are investigating any further causes and potential revisions we can apply to the data in future releases. For now, we have suppressed the most affected series in June and July 2025 only, due to quality concerns.",All tables
6,4,"Due to a technical ingest issue, a small number of adverts have been irretrievably missed from this month's data. This will only affect some adverts which were posted between 28th and 31st July, 2025. Please be aware that there may be a small number of adverts missing when interpreting this month's data",All tables
7,5,"Please note that the sum of English regions does not equal the England total. This is to do with the way Textkernel assigns geographies to adverts. To assign job adverts to a country, adverts are first assigned to a local authority level and then assigned to English region or country. However, if a local authority or region is not detailed on the advert then it can be assigned directly to country level if that is known.",Table 1
8,6,"Users should be aware that we noticed a drop in the number of new adverts in June 2026. The drop occurred in the underlying data received, as some sources had dropped off the deliveries. We have suppressed the most affected series in June 2026 only, due to quality concerns.",All tables
9,7,"In the July 2026 publication, we have partially imputed the data from October 2025 to February 2026 and June 2026. This is due to issues with a major Textkernel source, from which we were unable to obtain accurate information for this period. These issues included a high volume of duplicate adverts and, more recently, Textkernel being unable to scrape the website. The adjustment applied to the data has been calculated based on the average trend of the source for the past year, and it has been applied consistently across every table. Hence, users should treat with caution any individual odd month-on-month trends during those periods, which are more likely to be the case for more granular occupation and geography series, and focus more on the longer term trends. Please note, some of the tables may now not sum up due to rounding.",All tables

In [20]:
# Main analysis period: January 2023 to May 2025
digital_demand_main = digital_demand[
    (digital_demand["Month"] >= "2023-01-01") &
    (digital_demand["Month"] <= "2025-05-01")
].copy()

print("Rows and columns:", digital_demand_main.shape)
print("Start:", digital_demand_main["Month"].min())
print("End:", digital_demand_main["Month"].max())

print("\nMissing values:")
print(digital_demand_main.isnull().sum())

Rows and columns: (29, 6)
Start: 2023-01-01 00:00:00
End: 2025-05-01 00:00:00

Missing values:
Month                                                       0
2134 Programmers and software development professionals     0
2135 Cyber security professionals                           0
2433 Actuaries, economists and statisticians                0
3133 Database administrators and web content technicians    0
3544 Data analysts                                          0
dtype: int64

In [21]:
output_path = r"D:\MScProjects\labour-market-intelligence\data\processed\digital_demand_2023_2025.csv"

digital_demand_main.to_csv(output_path, index=False)

print("Saved successfully!")
print(output_path)

Saved successfully!
D:\MScProjects\labour-market-intelligence\data\processed\digital_demand_2023_2025.csv

In [25]:
import os

print(os.path.exists("D:\MScProjects\labour-market-intelligence\data\processed\digital_demand_2023_2025.csv"))

True

<>:3: SyntaxWarning: invalid escape sequence '\M'
<>:3: SyntaxWarning: invalid escape sequence '\M'
C:\Users\aksha\AppData\Local\Temp\ipykernel_6324\1911979006.py:3: SyntaxWarning: invalid escape sequence '\M'
  print(os.path.exists("D:\MScProjects\labour-market-intelligence\data\processed\digital_demand_2023_2025.csv"))

In [26]:
test_df = pd.read_csv(output_path)

print(test_df.shape)
test_df.head()

(29, 6)

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
0,2023-01-01,25269.0,3712.0,3993.0,2397.0,3606.0
1,2023-02-01,25118.0,3367.0,3131.0,2084.0,3358.0
2,2023-03-01,21905.0,3073.0,2908.0,1883.0,3261.0
3,2023-04-01,15409.0,2511.0,2473.0,1507.0,2462.0
4,2023-05-01,17787.0,2923.0,3069.0,1958.0,2962.0