In [1]:
import pandas as pd

salary_file = r"D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_Online_Job_Advert_Salaries_2017_2025.xlsx"

salary_excel = pd.ExcelFile(salary_file)

salary_excel.sheet_names

['Cover sheet',
 'Table of contents',
 'Notes',
 'Table 1',
 'Table 2',
 'Table 3',
 'Table 4',
 'Table 5',
 'Table 6',
 'Table 7',
 'Table 8',
 'Table 9',
 'Table 10',
 'Table 11',
 'Table 12',
 'Table 13',
 'Table 14',
 'Table 15',
 'Table 16',
 'Table 17',
 'Table 18',
 'Table 19',
 'Table 20',
 'Table 21',
 'Table 22',
 'Table 23',
 'Table 24',
 'Table 25',
 'Table 26',
 'Table 27',
 'Table 28',
 'Table 29',
 'Table 30',
 'Table 31',
 'Table 32',
 'Table 33',
 'Table 34',
 'Table 35',
 'Table 36',
 'Table 37',
 'Table 38',
 'Table 39']

In [2]:
for sheet in salary_excel.sheet_names[3:]:  # Skip cover, contents and notes
    print(f"\n===== {sheet} =====")

    temp = pd.read_excel(salary_file, sheet_name=sheet, header=None)

    print(temp.head(8))

===== Table 1 =====
                                                 0    \
0  Table 1: Mean asking salary of live online job...
1  Mean of minimum, mid-point, and maximum asking...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                            Country
5                                           Total UK
6                                           Total UK
7                                           Total UK

                          1       2       3       4       5       6       7    \
0                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
1                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
2                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
3                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
4                 Salary Type  Jan-17  Feb-17  Mar-17  Apr-17  May-17  Jun-17
5        Lowest asking salary   35200   34800   34700   35000   34700   34000
6  Middle point asking salary   38400   37900   37700   38000   37700   37000
7       Highest asking salary   41200   40500   40300   40500   40300   39500

      8       9    ...     93      94      95      96      97      98   \
0     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
4  Jul-17  Aug-17  ...  Aug-24  Sep-24  Oct-24  Nov-24  Dec-24  Jan-25
5   34300   34200  ...   36600   36900   36700   36800   37500   37700
6   37200   37000  ...   39200   39500   39400   39500   40300   40500
7   39700   39400  ...   41800   42200   42100   42200   43200   43300

      99      100     101     102
0     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN
4  Feb-25  Mar-25  Apr-25  May-25
5   37900   37700   37700   38300
6   40600   40400   40500   41000
7   43400   43100   43200   43800

[8 rows x 103 columns]

===== Table 2 =====
                                                 0    \
0  Table 2: Median asking salary of live online j...
1  Median of minimum, mid-point, and maximum aski...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                            Country
5                                           Total UK
6                                           Total UK
7                                           Total UK

                          1       2       3       4       5       6       7    \
0                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
1                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
2                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
3                         NaN     NaN     NaN     NaN     NaN     NaN     NaN
4                 Salary Type  Jan-17  Feb-17  Mar-17  Apr-17  May-17  Jun-17
5        Lowest asking salary   26000   25000   25400   26000   25700   25000
6  Middle point asking salary   29100   29000   29000   29000   29000   28100
7       Highest asking salary   31200   30800   30300   31000   31200   30000

      8       9    ...     93      94      95      96      97      98   \
0     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN
4  Jul-17  Aug-17  ...  Aug-24  Sep-24  Oct-24  Nov-24  Dec-24  Jan-25
5   25000   25000  ...   29500   29800   30000   30000   30000   30000
6   28500   28100  ...   31200   31300   31500   31900   32500   33000
7   30000   30000  ...   33300   33300   33500   34000   35000   35000

      99      100     101     102
0     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN
4  Feb-25  Mar-25  Apr-25  May-25
5   30000   30000   30000   30200
6   32600   32500   32500   33000
7   35000   35000   35000   35000

[8 rows x 103 columns]

===== Table 3 =====
                                                 0                     1    \
0  Table 3: Deciles of asking salary of live onli...                   NaN
1  Select deciles of minimum, mid-point, and maxi...                   NaN
2  This worksheet contains one table. Accompanyin...                   NaN
3                                   Back to contents                   NaN
4                                            Country           Salary Type
5                                           Total UK  Lowest asking salary
6                                           Total UK  Lowest asking salary
7                                           Total UK  Lowest asking salary

          2       3       4       5       6       7       8       9    ...  \
0         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN  ...
1         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN  ...
2         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN  ...
3         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN  ...
4      Decile  Jan-17  Feb-17  Mar-17  Apr-17  May-17  Jun-17  Jul-17  ...
5  1st Decile   15600   15600   15600   15600   15600   15600   15600  ...
6  2nd Decile   18000   17700   17700   17700   17700   17700   17500  ...
7  3rd Decile   20000   20000   20000   20000   20000   19800   19900  ...

      94      95      96      97      98      99      100     101     102  \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4  Aug-24  Sep-24  Oct-24  Nov-24  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25
5   22100   22100   22100   22100   22100   22400   22700   22900   23000
6   23900   23900   23900   23900   24000   24100   24200   24500   25000
7   25000   25000   25000   25000   25000   25500   25600   25800   26000

      103
0     NaN
1     NaN
2     NaN
3     NaN
4  May-25
5   23000
6   25300
7   26100

[8 rows x 104 columns]

===== Table 4 =====
                                                 0    \
0  Table 4: Median asking salary of live online j...
1  Median of mid-point asking salaries of live jo...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 1 digit code
5                                                  1
6                                                  2
7                                                  3

                                        1       2       3       4       5    \
0                                       NaN     NaN     NaN     NaN     NaN
1                                       NaN     NaN     NaN     NaN     NaN
2                                       NaN     NaN     NaN     NaN     NaN
3                                       NaN     NaN     NaN     NaN     NaN
4                         SOC 1 digit label  Jan-17  Feb-17  Mar-17  Apr-17
5  Managers, directors and senior officials   37500   37500   37500   38900
6                  Professional occupations   40000   39000   39000   39500
7        Associate professional occupations   30000   29500   29500   30000

      6       7       8       9    ...     93      94      95      96   \
0     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4  May-17  Jun-17  Jul-17  Aug-17  ...  Aug-24  Sep-24  Oct-24  Nov-24
5   37500   37500   37500   37500  ...   42000   42000   42500   42500
6   39000   38500   39000   39300  ...   45500   45800   45700   45700
7   30000   30000   30000   29800  ...   32200   32500   32500   32500

      97      98      99      100     101     102
0     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN
4  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25  May-25
5   43500   43700   44000   43500   43000   43600
6   46200   46800   46900   46900   46900   47500
7   33200   33300   33200   33000   33300   33700

[8 rows x 103 columns]

===== Table 5 =====
                                                 0    \
0  Table 5: Deciles of asking salary of live onli...
1  Select deciles of mid-point asking salaries of...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 1 digit code
5                                                  1
6                                                  1
7                                                  1

                                        1           2       3       4    \
0                                       NaN         NaN     NaN     NaN
1                                       NaN         NaN     NaN     NaN
2                                       NaN         NaN     NaN     NaN
3                                       NaN         NaN     NaN     NaN
4                         SOC 1 digit label      Decile  Jan-17  Feb-17
5  Managers, directors and senior officials  1st Decile   20000   20000
6  Managers, directors and senior officials  2nd Decile   25000   25000
7  Managers, directors and senior officials  3rd Decile   29000   29000

      5       6       7       8       9    ...     94      95      96   \
0     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
4  Mar-17  Apr-17  May-17  Jun-17  Jul-17  ...  Aug-24  Sep-24  Oct-24
5   19800   19800   19800   20000   20000  ...   25000   25100   25200
6   24800   25000   25000   25000   25000  ...   28500   28800   29000
7   29000   29500   29000   29500   29700  ...   32500   32500   32500

      97      98      99      100     101     102     103
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4  Nov-24  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25  May-25
5   25500   25600   25900   26000   26000   26000   26100
6   29100   29800   30000   30000   30000   30000   30000
7   33000   33800   34000   34000   34000   34000   34000

[8 rows x 104 columns]

===== Table 6 =====
                                                 0    \
0  Table 6: Median asking salary of live online j...
1  Median of mid-point asking salaries of live jo...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 2 digit code
5                                                 11
6                                                 12
7                                                 21

                                                 1       2       3       4    \
0                                                NaN     NaN     NaN     NaN
1                                                NaN     NaN     NaN     NaN
2                                                NaN     NaN     NaN     NaN
3                                                NaN     NaN     NaN     NaN
4                                  SOC 2 digit label  Jan-17  Feb-17  Mar-17
5                   Corporate managers and directors   44000   43500   44000
6                     Other managers and proprietors   31000   31000   30800
7  Science, research, engineering and technology ...   42500   42500   42500

      5       6       7       8       9    ...     93      94      95   \
0     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN
4  Apr-17  May-17  Jun-17  Jul-17  Aug-17  ...  Aug-24  Sep-24  Oct-24
5   45000   44000   44000   44000   43100  ...   50000   50000   50000
6   31000   31500   32000   31500   30500  ...   35000   35000   35000
7   42500   42500   42500   42500   42500  ...   47800   48500   48300

      96      97      98      99      100     101     102
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4  Nov-24  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25  May-25
5   50000   50000   50000   50000   50000   50000   50000
6   35000   36000   36300   36400   36400   36400   36400
7   48400   49400   49500   50000   50000   50000   50000

[8 rows x 103 columns]

===== Table 7 =====
                                                 0    \
0  Table 7: Deciles of asking salary of live onli...
1  Select deciles of mid-point asking salaries of...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 2 digit code
5                                                 11
6                                                 11
7                                                 11

                                1           2       3       4       5    \
0                               NaN         NaN     NaN     NaN     NaN
1                               NaN         NaN     NaN     NaN     NaN
2                               NaN         NaN     NaN     NaN     NaN
3                               NaN         NaN     NaN     NaN     NaN
4                 SOC 2 digit label      Decile  Jan-17  Feb-17  Mar-17
5  Corporate managers and directors  1st Decile   22000   22000   21800
6  Corporate managers and directors  2nd Decile   28100   28000   28500
7  Corporate managers and directors  3rd Decile   34000   34000   34000

      6       7       8       9    ...     94      95      96      97   \
0     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4  Apr-17  May-17  Jun-17  Jul-17  ...  Aug-24  Sep-24  Oct-24  Nov-24
5   22000   21500   21500   21500  ...   26700   26700   26800   27000
6   29500   28000   28300   29000  ...   32500   32500   32500   32500
7   35000   34300   34000   34900  ...   39000   39000   39000   39000

      98      99      100     101     102     103
0     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN
4  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25  May-25
5   27000   27500   27500   27500   27500   27500
6   33400   33700   34000   34000   33500   33600
7   40000   40000   40000   40000   40000   40000

[8 rows x 104 columns]

===== Table 8 =====
                                                 0    \
0  Table 8: Median asking salary of live online j...
1  Median of mid-point asking salaries of live jo...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 3 digit code
5                                                111
6                                                112
7                                                113

                                     1       2       3       4       5    \
0                                    NaN     NaN     NaN     NaN     NaN
1                                    NaN     NaN     NaN     NaN     NaN
2                                    NaN     NaN     NaN     NaN     NaN
3                                    NaN     NaN     NaN     NaN     NaN
4                      SOC 3 digit label  Jan-17  Feb-17  Mar-17  Apr-17
5  Chief Executives and Senior Officials   27300   25000   22600   26000
6      Production Managers and Directors   43700   43000   44000   45000
7      Functional Managers and Directors   45000   45000   46500   47500

      6       7       8       9    ...     93      94      95      96   \
0     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4  May-17  Jun-17  Jul-17  Aug-17  ...  Aug-24  Sep-24  Oct-24  Nov-24
5   23500   22000   21500   21100  ...   30600   30200   29700   31100
6   45000   45000   45000   44700  ...   50000   50000   50000   49500
7   45500   45500   47400   45800  ...   53000   53000   53200   54000

      97      98      99      100     101     102
0     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN
4  Dec-24  Jan-25  Feb-25  Mar-25  Apr-25  May-25
5   32200   33200   35000   33300   32500   32200
6   50000   50000   50000   50000   50000   50000
7   55000   55000   55000   55000   55000   55000

[8 rows x 103 columns]

===== Table 9 =====
                                                 0    \
0  Table 9: Deciles of asking salary of live onli...
1  Select deciles of mid-point asking salaries of...
2  This worksheet contains one table. Accompanyin...
3                                   Back to contents
4                                   SOC 3 digit code
5                                                111
6                                                111
7                                                111

                                     1           2       3       4       5    \
0                                    NaN         NaN     NaN     NaN     NaN
1                                    NaN         NaN     NaN     NaN     NaN
2                                    NaN         NaN     NaN     NaN     NaN
3                                    NaN         NaN     NaN     NaN     NaN
4                      SOC 3 digit label      Decile  Jan-17  Feb-17  Mar-17
5  Chief Executives and Senior Officials  1st Decile   15000   15000   15000
6  Chief Executives and Senior Officials  2nd Decile   16100   16000   15900
7  Chief Executives and Senior Officials  3rd Decile   17400   17000   16800

      6       7       8       9    ...     94      95      96      97   \
0     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4  Apr-17  May-17  Jun-17  Jul-17  ...  Aug-24  Sep-24  Oct-24  Nov-24
5   15600   15600   15600   15600  ...   23700   23700   23700   23700
6   16100   16000   16000   16000  ...   24000   24000   24000   24100
7   17200   17100   16800   16900  ...   25100   25000   25000   25400


In [3]:
it_jobs = [
    "Programmers and software development professionals",
    "Cyber security professionals",
    "Actuaries, economists and statisticians",
    "Database administrators and web content technicians",
    "Data analysts"
]

In [4]:
salary_raw = pd.read_excel(
    salary_file,
    sheet_name="Table 11",
    header=None
)

salary_raw.head(20)

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,Table 11: Median asking salary of live online ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Median of mid-point asking salaries of live jo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,This worksheet contains one table. Accompanyin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SOC 4 digit code,SOC 4 digit label,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,...,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25
5,1111,Chief executives and senior officials,47500,46500,45000,52500,49000,47500,50000,45000,...,65000,65000,65000,67500,65000,65000,70000,70000,70000,70000
6,1112,Elected officers and representatives,16600,16600,16600,16600,16800,16600,17000,17200,...,25100,25400,25200,25300,25400,25400,25400,25500,26000,26100
7,1121,Production managers and directors in manufactu...,40000,40000,40000,40000,40000,40000,40000,39500,...,44500,45000,45000,45000,45000,45000,45000,45000,45000,45000
8,1122,Production managers and directors in construction,47500,47500,47500,47500,47500,47500,47500,48000,...,55000,55000,55000,54700,55000,55000,55000,55000,55000,55000
9,1123,Production managers and directors in mining an...,40000,40000,40000,42500,40000,40000,40000,39100,...,50200,48000,45000,48400,50000,48600,48500,50000,47500,45000
10,1131,Financial managers and directors,45000,45000,46800,46800,47000,45000,45000,45000,...,54000,54600,55000,55000,55000,55000,55000,55000,55000,55000
11,1132,"Marketing, sales and advertising directors",60000,57500,57500,56000,55000,57000,57500,57500,...,65000,65000,65000,65000,65000,65000,65000,65000,65000,65000
12,1133,Public relations and communications directors,57500,55000,57600,59500,57900,54000,53600,55200,...,61000,62000,60000,62000,63000,62400,62100,62900,62900,62900
13,1134,Purchasing managers and directors,45000,45000,46800,46600,46700,50000,50000,47000,...,54100,52500,52500,52500,55000,53000,52500,54000,54000,55000
14,1135,Charitable organisation managers and directors,27500,28000,27500,24500,23900,23700,27000,26500,...,42600,40200,40000,40000,41600,44500,45000,41500,47500,42900
15,1136,Human resource managers and directors,37500,37500,37500,40000,37500,37500,40000,39000,...,45000,45000,45000,45000,45000,45000,45700,46200,45100,45100
16,1137,Information technology directors,65000,62500,62300,60900,62500,62500,64500,65000,...,70000,70000,70000,70000,72700,72500,72600,72500,73500,75000
17,1139,Functional managers and directors n.e.c.,59100,58500,60000,59000,56300,55000,55000,55000,...,61300,61800,62600,63200,63000,64000,65000,64100,64000,63100
18,1140,"Directors in logistics, warehousing and transport",55000,59300,60000,60000,52700,52300,60000,56200,...,50800,51500,45400,49500,47700,49400,44600,44500,45000,52500
19,1150,Managers and directors in retail and wholesale,27800,27500,27500,27000,27500,27500,27000,26000,...,29600,29800,29800,30000,30000,30000,30400,30400,30400,30500

In [5]:
salary_raw[salary_raw.astype(str).apply(
    lambda row: row.str.contains(
        "Programmers|Cyber|Data analysts|Database|Actuaries",
        case=False,
        na=False
    ).any(),
    axis=1
)]

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
64,2134,Programmers and software development professio...,45000,45000,45000,45000,45000,45000,45000,45000,...,52600,52500,52500,52500,52500,52500,54000,55000,55000,55000
65,2135,Cyber security professionals,60000,57500,57500,57500,57500,57500,55000,55000,...,55000,55000,55000,56000,56200,55000,57500,58100,58000,60000
120,2433,"Actuaries, economists and statisticians",50000,50000,50000,50000,50000,50000,50000,50000,...,55000,54200,52000,53400,55000,55000,54900,55000,55000,57500
154,3133,Database administrators and web content techni...,31000,30000,31100,32000,32000,30000,30000,30000,...,31200,31000,31000,31500,32500,32000,32000,32000,31500,32000
196,3544,Data analysts,35000,35000,34300,34600,35000,35000,35000,35000,...,40000,40000,40000,40000,40000,40000,40000,40000,40000,40000

In [7]:
salary_raw = pd.read_excel(
    salary_file,
    sheet_name="Table 11",
    header=None
)

keywords = [
    "Programmers",
    "Cyber",
    "Data analysts",
    "Database",
    "Actuaries"
]

for keyword in keywords:
    print(f"\n----- {keyword} -----")
    matches = salary_raw[
        salary_raw.astype(str).apply(
            lambda row: row.str.contains(keyword, case=False, na=False).any(),
            axis=1
        )
    ]
    print(matches)

----- Programmers -----
     0                                                  1      2      3    \
64  2134  Programmers and software development professio...  45000  45000

      4      5      6      7      8      9    ...    93     94     95     96   \
64  45000  45000  45000  45000  45000  45000  ...  52600  52500  52500  52500

      97     98     99     100    101    102
64  52500  52500  54000  55000  55000  55000

[1 rows x 103 columns]

----- Cyber -----
     0                             1      2      3      4      5      6    \
65  2135  Cyber security professionals  60000  57500  57500  57500  57500

      7      8      9    ...    93     94     95     96     97     98     99   \
65  57500  55000  55000  ...  55000  55000  55000  56000  56200  55000  57500

      100    101    102
65  58100  58000  60000

[1 rows x 103 columns]

----- Data analysts -----
      0              1      2      3      4      5      6      7      8    \
196  3544  Data analysts  35000  35000  34300  34600  35000  35000  35000

       9    ...    93     94     95     96     97     98     99     100  \
196  35000  ...  40000  40000  40000  40000  40000  40000  40000  40000

       101    102
196  40000  40000

[1 rows x 103 columns]

----- Database -----
      0                                                  1      2      3    \
154  3133  Database administrators and web content techni...  31000  30000

       4      5      6      7      8      9    ...    93     94     95   \
154  31100  32000  32000  30000  30000  30000  ...  31200  31000  31000

       96     97     98     99     100    101    102
154  31500  32500  32000  32000  32000  31500  32000

[1 rows x 103 columns]

----- Actuaries -----
      0                                        1      2      3      4    \
120  2433  Actuaries, economists and statisticians  50000  50000  50000

       5      6      7      8      9    ...    93     94     95     96   \
120  50000  50000  50000  50000  50000  ...  55000  54200  52000  53400

       97     98     99     100    101    102
120  55000  55000  54900  55000  55000  57500

[1 rows x 103 columns]

In [8]:
salary = salary_raw.iloc[[64, 65, 120, 154, 196]].copy()

salary

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
64,2134,Programmers and software development professio...,45000,45000,45000,45000,45000,45000,45000,45000,...,52600,52500,52500,52500,52500,52500,54000,55000,55000,55000
65,2135,Cyber security professionals,60000,57500,57500,57500,57500,57500,55000,55000,...,55000,55000,55000,56000,56200,55000,57500,58100,58000,60000
120,2433,"Actuaries, economists and statisticians",50000,50000,50000,50000,50000,50000,50000,50000,...,55000,54200,52000,53400,55000,55000,54900,55000,55000,57500
154,3133,Database administrators and web content techni...,31000,30000,31100,32000,32000,30000,30000,30000,...,31200,31000,31000,31500,32500,32000,32000,32000,31500,32000
196,3544,Data analysts,35000,35000,34300,34600,35000,35000,35000,35000,...,40000,40000,40000,40000,40000,40000,40000,40000,40000,40000

In [9]:
salary_raw.iloc[:8, :15]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Table 11: Median asking salary of live online ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Median of mid-point asking salaries of live jo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,This worksheet contains one table. Accompanyin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SOC 4 digit code,SOC 4 digit label,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,Sep-17,Oct-17,Nov-17,Dec-17,Jan-18
5,1111,Chief executives and senior officials,47500,46500,45000,52500,49000,47500,50000,45000,45000,44500,45000,44000,45000
6,1112,Elected officers and representatives,16600,16600,16600,16600,16800,16600,17000,17200,17200,17000,17200,17400,17500
7,1121,Production managers and directors in manufactu...,40000,40000,40000,40000,40000,40000,40000,39500,40000,39500,40000,40000,40000

In [10]:
# Read Table 11 properly
salary_df = pd.read_excel(
    salary_file,
    sheet_name="Table 11",
    header=4
)

salary_df.head()

,SOC 4 digit code,SOC 4 digit label,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,...,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25
0,1111,Chief executives and senior officials,47500,46500,45000,52500,49000,47500,50000,45000,...,65000,65000,65000,67500,65000,65000,70000,70000,70000,70000
1,1112,Elected officers and representatives,16600,16600,16600,16600,16800,16600,17000,17200,...,25100,25400,25200,25300,25400,25400,25400,25500,26000,26100
2,1121,Production managers and directors in manufactu...,40000,40000,40000,40000,40000,40000,40000,39500,...,44500,45000,45000,45000,45000,45000,45000,45000,45000,45000
3,1122,Production managers and directors in construction,47500,47500,47500,47500,47500,47500,47500,48000,...,55000,55000,55000,54700,55000,55000,55000,55000,55000,55000
4,1123,Production managers and directors in mining an...,40000,40000,40000,42500,40000,40000,40000,39100,...,50200,48000,45000,48400,50000,48600,48500,50000,47500,45000

In [11]:
selected_salary = salary_df[
    salary_df["SOC 4 digit code"].isin([
        2134,
        2135,
        2433,
        3133,
        3544
    ])
]

selected_salary

Empty DataFrame
Columns: [SOC 4 digit code, SOC 4 digit label, Jan-17, Feb-17, Mar-17, Apr-17, May-17, Jun-17, Jul-17, Aug-17, Sep-17, Oct-17, Nov-17, Dec-17, Jan-18, Feb-18, Mar-18, Apr-18, May-18, Jun-18, Jul-18, Aug-18, Sep-18, Oct-18, Nov-18, Dec-18, Jan-19, Feb-19, Mar-19, Apr-19, May-19, Jun-19, Jul-19, Aug-19, Sep-19, Oct-19, Nov-19, Dec-19, Jan-20, Feb-20, Mar-20, Apr-20, May-20, Jun-20, Jul-20, Aug-20, Sep-20, Oct-20, Nov-20, Dec-20, Jan-21, Feb-21, Mar-21, Apr-21, May-21, Jun-21, Jul-21, Aug-21, Sep-21, Oct-21, Nov-21, Dec-21, Jan-22, Feb-22, Mar-22, Apr-22, May-22, Jun-22, Jul-22, Aug-22, Sep-22, Oct-22, Nov-22, Dec-22, Jan-23, Feb-23, Mar-23, Apr-23, May-23, Jun-23, Jul-23, Aug-23, Sep-23, Oct-23, Nov-23, Dec-23, Jan-24, Feb-24, Mar-24, Apr-24, May-24, Jun-24, Jul-24, Aug-24, Sep-24, Oct-24, Nov-24, Dec-24, Jan-25, Feb-25, ...]
Index: []

[0 rows x 103 columns]

In [12]:
salary_df.dtypes

SOC 4 digit code       str
SOC 4 digit label      str
Jan-17               int64
Feb-17               int64
Mar-17               int64
                     ...
Jan-25               int64
Feb-25               int64
Mar-25               int64
Apr-25               int64
May-25               int64
Length: 103, dtype: object

In [13]:
salary_df[["SOC 4 digit code", "SOC 4 digit label"]].head(10)

  SOC 4 digit code                                  SOC 4 digit label
0             1111              Chief executives and senior officials
1             1112               Elected officers and representatives
2             1121  Production managers and directors in manufactu...
3             1122  Production managers and directors in construction
4             1123  Production managers and directors in mining an...
5             1131                   Financial managers and directors
6             1132         Marketing, sales and advertising directors
7             1133      Public relations and communications directors
8             1134                  Purchasing managers and directors
9             1135     Charitable organisation managers and directors

In [14]:
salary_df["SOC 4 digit code"] = pd.to_numeric(
    salary_df["SOC 4 digit code"],
    errors="coerce"
)

In [15]:
selected_salary = salary_df[
    salary_df["SOC 4 digit code"].isin([2134, 2135, 2433, 3133, 3544])
]

selected_salary

,SOC 4 digit code,SOC 4 digit label,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,...,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25
59,2134.0,Programmers and software development professio...,45000,45000,45000,45000,45000,45000,45000,45000,...,52600,52500,52500,52500,52500,52500,54000,55000,55000,55000
60,2135.0,Cyber security professionals,60000,57500,57500,57500,57500,57500,55000,55000,...,55000,55000,55000,56000,56200,55000,57500,58100,58000,60000
115,2433.0,"Actuaries, economists and statisticians",50000,50000,50000,50000,50000,50000,50000,50000,...,55000,54200,52000,53400,55000,55000,54900,55000,55000,57500
149,3133.0,Database administrators and web content techni...,31000,30000,31100,32000,32000,30000,30000,30000,...,31200,31000,31000,31500,32500,32000,32000,32000,31500,32000
191,3544.0,Data analysts,35000,35000,34300,34600,35000,35000,35000,35000,...,40000,40000,40000,40000,40000,40000,40000,40000,40000,40000

In [16]:
salary_df["SOC 4 digit code"] = salary_df["SOC 4 digit code"].astype(str).str.strip()

In [17]:
selected_salary = salary_df[
    salary_df["SOC 4 digit code"].isin([
        "2134",
        "2135",
        "2433",
        "3133",
        "3544"
    ])
]

selected_salary

Empty DataFrame
Columns: [SOC 4 digit code, SOC 4 digit label, Jan-17, Feb-17, Mar-17, Apr-17, May-17, Jun-17, Jul-17, Aug-17, Sep-17, Oct-17, Nov-17, Dec-17, Jan-18, Feb-18, Mar-18, Apr-18, May-18, Jun-18, Jul-18, Aug-18, Sep-18, Oct-18, Nov-18, Dec-18, Jan-19, Feb-19, Mar-19, Apr-19, May-19, Jun-19, Jul-19, Aug-19, Sep-19, Oct-19, Nov-19, Dec-19, Jan-20, Feb-20, Mar-20, Apr-20, May-20, Jun-20, Jul-20, Aug-20, Sep-20, Oct-20, Nov-20, Dec-20, Jan-21, Feb-21, Mar-21, Apr-21, May-21, Jun-21, Jul-21, Aug-21, Sep-21, Oct-21, Nov-21, Dec-21, Jan-22, Feb-22, Mar-22, Apr-22, May-22, Jun-22, Jul-22, Aug-22, Sep-22, Oct-22, Nov-22, Dec-22, Jan-23, Feb-23, Mar-23, Apr-23, May-23, Jun-23, Jul-23, Aug-23, Sep-23, Oct-23, Nov-23, Dec-23, Jan-24, Feb-24, Mar-24, Apr-24, May-24, Jun-24, Jul-24, Aug-24, Sep-24, Oct-24, Nov-24, Dec-24, Jan-25, Feb-25, ...]
Index: []

[0 rows x 103 columns]

In [18]:
salary_df["SOC 4 digit code"].unique()[:20]

<ArrowStringArray>
['1111.0', '1112.0', '1121.0', '1122.0', '1123.0', '1131.0', '1132.0',
 '1133.0', '1134.0', '1135.0', '1136.0', '1137.0', '1139.0', '1140.0',
 '1150.0', '1161.0', '1162.0', '1163.0', '1171.0', '1172.0']
Length: 20, dtype: str

In [19]:
salary_df[
    salary_df["SOC 4 digit label"].str.contains(
        "Programmers|Cyber|Data analysts|Database|Actuaries",
        case=False,
        na=False
    )
]

,SOC 4 digit code,SOC 4 digit label,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,...,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25
59,2134.0,Programmers and software development professio...,45000,45000,45000,45000,45000,45000,45000,45000,...,52600,52500,52500,52500,52500,52500,54000,55000,55000,55000
60,2135.0,Cyber security professionals,60000,57500,57500,57500,57500,57500,55000,55000,...,55000,55000,55000,56000,56200,55000,57500,58100,58000,60000
115,2433.0,"Actuaries, economists and statisticians",50000,50000,50000,50000,50000,50000,50000,50000,...,55000,54200,52000,53400,55000,55000,54900,55000,55000,57500
149,3133.0,Database administrators and web content techni...,31000,30000,31100,32000,32000,30000,30000,30000,...,31200,31000,31000,31500,32500,32000,32000,32000,31500,32000
191,3544.0,Data analysts,35000,35000,34300,34600,35000,35000,35000,35000,...,40000,40000,40000,40000,40000,40000,40000,40000,40000,40000

In [24]:
salary_long["Month"].head(10)

Series([], Name: Month, dtype: datetime64[s])

In [25]:
salary_long["Month"].dtype

dtype('<M8[s]')

In [26]:
selected_salary.columns.tolist()

['SOC 4 digit code',
 'SOC 4 digit label',
 'Jan-17',
 'Feb-17',
 'Mar-17',
 'Apr-17',
 'May-17',
 'Jun-17',
 'Jul-17',
 'Aug-17',
 'Sep-17',
 'Oct-17',
 'Nov-17',
 'Dec-17',
 'Jan-18',
 'Feb-18',
 'Mar-18',
 'Apr-18',
 'May-18',
 'Jun-18',
 'Jul-18',
 'Aug-18',
 'Sep-18',
 'Oct-18',
 'Nov-18',
 'Dec-18',
 'Jan-19',
 'Feb-19',
 'Mar-19',
 'Apr-19',
 'May-19',
 'Jun-19',
 'Jul-19',
 'Aug-19',
 'Sep-19',
 'Oct-19',
 'Nov-19',
 'Dec-19',
 'Jan-20',
 'Feb-20',
 'Mar-20',
 'Apr-20',
 'May-20',
 'Jun-20',
 'Jul-20',
 'Aug-20',
 'Sep-20',
 'Oct-20',
 'Nov-20',
 'Dec-20',
 'Jan-21',
 'Feb-21',
 'Mar-21',
 'Apr-21',
 'May-21',
 'Jun-21',
 'Jul-21',
 'Aug-21',
 'Sep-21',
 'Oct-21',
 'Nov-21',
 'Dec-21',
 'Jan-22',
 'Feb-22',
 'Mar-22',
 'Apr-22',
 'May-22',
 'Jun-22',
 'Jul-22',
 'Aug-22',
 'Sep-22',
 'Oct-22',
 'Nov-22',
 'Dec-22',
 'Jan-23',
 'Feb-23',
 'Mar-23',
 'Apr-23',
 'May-23',
 'Jun-23',
 'Jul-23',
 'Aug-23',
 'Sep-23',
 'Oct-23',
 'Nov-23',
 'Dec-23',
 'Jan-24',
 'Feb-24',
 'Mar-24',
 'Apr-24',
 'May-24',
 'Jun-24',
 'Jul-24',
 'Aug-24',
 'Sep-24',
 'Oct-24',
 'Nov-24',
 'Dec-24',
 'Jan-25',
 'Feb-25',
 'Mar-25',
 'Apr-25',
 'May-25']

In [28]:
salary_long = selected_salary.melt(
    id_vars=["SOC 4 digit code", "SOC 4 digit label"],
    var_name="Month",
    value_name="Median_Salary"
)

print(salary_long.shape)
salary_long.head()

(0, 4)

Empty DataFrame
Columns: [SOC 4 digit code, SOC 4 digit label, Month, Median_Salary]
Index: []

In [29]:
print(selected_salary.shape)
selected_salary.head()
salary_df[
    salary_df["SOC 4 digit label"].str.contains(
        "Programmers|Cyber|Actuaries|Database|Data analysts",
        case=False,
        na=False
    )
].shape

(0, 103)

(5, 103)

In [30]:
selected_salary = salary_df[
    salary_df["SOC 4 digit label"].str.contains(
        "Programmers|Cyber|Actuaries|Database|Data analysts",
        case=False,
        na=False
    )
].copy()

print(selected_salary.shape)

(5, 103)

In [31]:
salary_long = selected_salary.melt(
    id_vars=["SOC 4 digit code", "SOC 4 digit label"],
    var_name="Month",
    value_name="Median_Salary"
)

print(salary_long.shape)
salary_long.head()

(505, 4)

,SOC 4 digit code,SOC 4 digit label,Month,Median_Salary
0,2134.0,Programmers and software development professio...,Jan-17,45000
1,2135.0,Cyber security professionals,Jan-17,60000
2,2433.0,"Actuaries, economists and statisticians",Jan-17,50000
3,3133.0,Database administrators and web content techni...,Jan-17,31000
4,3544.0,Data analysts,Jan-17,35000

In [32]:
salary_long["Month"].unique()[:10]

<ArrowStringArray>
['Jan-17', 'Feb-17', 'Mar-17', 'Apr-17', 'May-17', 'Jun-17', 'Jul-17',
 'Aug-17', 'Sep-17', 'Oct-17']
Length: 10, dtype: str

In [33]:
salary_long["Month"] = pd.to_datetime(
    salary_long["Month"],
    format="%b-%y"
)

print(salary_long["Month"].min())
print(salary_long["Month"].max())
print(salary_long.shape)

2017-01-01 00:00:00
2025-05-01 00:00:00
(505, 4)

In [34]:
salary_long = salary_long[
    (salary_long["Month"] >= "2023-01-01") &
    (salary_long["Month"] <= "2025-05-01")
].copy()

print(salary_long.shape)
print(salary_long["Month"].min())
print(salary_long["Month"].max())

(145, 4)
2023-01-01 00:00:00
2025-05-01 00:00:00

In [35]:
salary_long = salary_long.rename(columns={
    "SOC 4 digit code": "SOC_Code",
    "SOC 4 digit label": "Occupation"
})

salary_long.head()

,SOC_Code,Occupation,Month,Median_Salary
360,2134.0,Programmers and software development professio...,2023-01-01,52500
361,2135.0,Cyber security professionals,2023-01-01,55000
362,2433.0,"Actuaries, economists and statisticians",2023-01-01,55000
363,3133.0,Database administrators and web content techni...,2023-01-01,30000
364,3544.0,Data analysts,2023-01-01,39000

In [36]:
output_path = r"D:\MScProjects\labour-market-intelligence\data\processed\salary_2023_2025.csv"

salary_long.to_csv(output_path, index=False)

print("Saved successfully!")
print(output_path)

Saved successfully!
D:\MScProjects\labour-market-intelligence\data\processed\salary_2023_2025.csv

In [37]:
print(salary_long.shape)
salary_long.info()
salary_long.head()

(145, 4)
<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 360 to 504
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SOC_Code       145 non-null    str
 1   Occupation     145 non-null    str
 2   Month          145 non-null    datetime64[us]
 3   Median_Salary  145 non-null    object
dtypes: datetime64[us](1), object(1), str(2)
memory usage: 10.7+ KB

,SOC_Code,Occupation,Month,Median_Salary
360,2134.0,Programmers and software development professio...,2023-01-01,52500
361,2135.0,Cyber security professionals,2023-01-01,55000
362,2433.0,"Actuaries, economists and statisticians",2023-01-01,55000
363,3133.0,Database administrators and web content techni...,2023-01-01,30000
364,3544.0,Data analysts,2023-01-01,39000

In [ ]:
    salary_long.isnull().sum()

SOC_Code         0
Occupation       0
Month            0
Median_Salary    0
dtype: int64