In [1]:
from pathlib import Path

raw_path = Path(r"D:\MScProjects\labour-market-intelligence\data\raw")

for item in raw_path.iterdir():
    print(item.name)

job_adverts
onet
ons

In [2]:
from pathlib import Path

raw_path = Path(r"D:\MScProjects\labour-market-intelligence\data\raw")

# Find anything related to Local Authority
for p in raw_path.rglob("*"):
    if "Local_Authority" in p.name or "Local Authority" in p.name:
        print(p)

D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Local_Authority.zip

In [3]:
import zipfile

zip_path = r"D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Local_Authority.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    files = z.namelist()

for f in files:
    print(f)

PROV - Work Geography Table 7.10a   Paid hours worked - Basic 2023.xls
PROV - Work Geography Table 7.10b   Paid hours worked - Basic 2023 CV.xls
PROV - Work Geography Table 7.11a   Paid hours worked - Overtime 2023.xls
PROV - Work Geography Table 7.11b   Paid hours worked - Overtime 2023 CV.xls
PROV - Work Geography Table 7.1a   Weekly pay - Gross 2023.xls
PROV - Work Geography Table 7.1b   Weekly pay - Gross 2023 CV.xls
PROV - Work Geography Table 7.2a   Weekly pay - Excluding overtime 2023.xls
PROV - Work Geography Table 7.2b   Weekly pay - Excluding overtime 2023 CV.xls
PROV - Work Geography Table 7.3a   Basic Pay - Including other pay 2023.xls
PROV - Work Geography Table 7.3b   Basic Pay - Including other pay 2023 CV.xls
PROV - Work Geography Table 7.4a   Overtime pay 2023.xls
PROV - Work Geography Table 7.4b   Overtime pay 2023 CV.xls
PROV - Work Geography Table 7.5a   Hourly pay - Gross 2023.xls
PROV - Work Geography Table 7.5b   Hourly pay - Gross 2023 CV.xls
PROV - Work Geography Table 7.6a   Hourly pay - Excluding overtime 2023.xls
PROV - Work Geography Table 7.6b   Hourly pay - Excluding overtime 2023 CV.xls
PROV - Work Geography Table 7.7a   Annual pay - Gross 2023.xls
PROV - Work Geography Table 7.7b   Annual pay - Gross 2023 CV.xls
PROV - Work Geography Table 7.8a   Annual pay - Incentive 2023.xls
PROV - Work Geography Table 7.8b   Annual pay - Incentive 2023 CV.xls
PROV - Work Geography Table 7.9a   Paid hours worked - Total 2023.xls
PROV - Work Geography Table 7.9b   Paid hours worked - Total 2023 CV.xls

In [4]:
import zipfile
from pathlib import Path

zip_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Local_Authority.zip"
)

extract_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\processed\ashe_city"
)

extract_path.mkdir(parents=True, exist_ok=True)

target = "PROV - Work Geography Table 7.7a   Annual pay - Gross 2023.xls"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extract(target, extract_path)

print(extract_path / target)

D:\MScProjects\labour-market-intelligence\data\processed\ashe_city\PROV - Work Geography Table 7.7a   Annual pay - Gross 2023.xls

In [8]:
import pandas as pd

file_path = r"D:\MScProjects\labour-market-intelligence\data\processed\ashe_city\PROV - Work Geography Table 7.7a   Annual pay - Gross 2023.xls"

xls = pd.ExcelFile(file_path)

print(xls.sheet_names)

['Notes', 'All', 'Male', 'Female', 'Full-Time', 'Part-Time', 'Male Full-Time', 'Male Part-Time', 'Female Full-Time', 'Female Part-Time']

In [9]:
salary_city_raw = pd.read_excel(
    file_path,
    sheet_name="All",
    header=None
)

print(salary_city_raw.shape)

salary_city_raw.head(20)

(407, 20)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Table 7.7a Annual pay - Gross,NaN,For all employee jobs(a): United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Number,NaN,Annual,NaN,Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,of jobsb,NaN,percentage,NaN,percentage,Percentiles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Description,Code,(thousand),Median,change,Mean,change,10,20,25,30,40,60,70,75,80,90,NaN,NaN,NaN
5,United Kingdom,K02000001,22480,29669,6.8,35404,5.8,10186,16815,19783,21970,25802,34303,40000,43157,47248,60506,NaN,NaN,NaN
6,Great Britain,K03000001,21577,29800,6.8,35555,5.8,10206,16871,19857,22031,25893,34404,40122,43305,47396,60786,NaN,Key,Statistical robustness
7,England and Wales,K04000001,19682,29824,6.7,35764,5.7,10199,16852,19848,22019,25899,34402,40153,43430,47628,61317,NaN,CV <= 5%,Estimates are considered precise
8,England,E92000001,18661,29955,6.8,36074,5.7,10214,16927,19911,22097,26000,34593,40425,43726,47991,62002,NaN,CV > 5% and <= 10%,Estimates are considered reasonably precise
9,North East,E12000001,862,26576,6.2,29706,4.6,9751,15396,18172,20166,23356,30333,35020,37875,40974,49676,NaN,CV > 10% and <= 20%,Estimates are considered acceptable
10,Darlington UA,E06000005,43,26509,5.4,31166,1.9,13287,16435,19110,20689,23285,30936,36059,38673,41136,x,NaN,x = CV > 20%,Estimates are considered unreliable for practi...
11,Hartlepool UA,E06000001,26,25010,11.6,27557,6.9,9329,15092,15686,17650,21488,28421,33619,35558,40115,x,NaN,.. = disclosive,NaN
12,Middlesbrough UA,E06000002,43,26533,9.6,29904,8.1,10113,16109,18559,20037,23079,30341,34808,37875,42130,x,NaN,: = not applicable,NaN
13,Redcar and Cleveland UA,E06000003,27,25846,31.2,28010,19.3,x,x,x,x,x,x,x,x,x,x,NaN,- = nil or negligible,NaN
14,Stockton-on-Tees UA,E06000004,61,26223,0.3,31206,8.3,10977,15040,18552,20311,23398,29610,35599,38366,41453,x,NaN,NaN,NaN
15,County Durham UA,E06000047,147,26399,5.5,29310,4.9,8987,15302,17765,19999,23508,29621,34880,37486,40791,x,NaN,NaN,NaN
16,Northumberland UA,E06000057,79,25272,12,27813,-0.8,8724,13801,17108,19171,22436,28613,33642,36138,39355,x,NaN,NaN,NaN
17,Tyne and Wear Met County,E11000007,437,27087,6.1,30052,3.9,9932,15749,18544,20664,23600,30874,35134,38153,41425,50007,NaN,NaN,NaN
18,Gateshead,E08000037,73,25833,3.4,28842,4.3,8747,16223,18647,20674,23228,29401,34061,36366,40196,x,NaN,NaN,NaN
19,Newcastle upon Tyne,E08000021,154,28756,2.9,31919,2.3,11290,17673,19935,22166,25993,32554,37441,39857,42753,x,NaN,NaN,NaN

In [10]:
cities = salary_city_raw[
    salary_city_raw[0].astype(str).str.contains(
        "London|Manchester|Birmingham",
        case=False,
        na=False
    )
]

cities[[0, 1, 2, 3, 4, 5, 6]]

                                 0          1     2      3     4      5    6
32   Greater Manchester Met County  E11000001   907  28923   9.5  32941  6.1
35                      Manchester  E08000003   285  33458  11.1  38223  7.9
141                     Birmingham  E08000025   351  28648   0.1  33510 -1.3
206                        London   E12000007  3212  38943   5.8  52409  5.2
207                   Inner London  E13000001  2073  44230   6.1  61579  3.5
209                 City of London  E09000001   411  60000     0  93201   -3
222                   Outer London  E13000002  1135  30875   2.2  35713  6.5

In [11]:
city_salary_2023 = salary_city_raw[
    salary_city_raw[1].isin([
        "E12000007",  # London
        "E08000003",  # Manchester
        "E08000025"   # Birmingham
    ])
][[0, 1, 3]].copy()

city_salary_2023.columns = [
    "City",
    "Area_Code",
    "Median_Annual_Salary"
]

city_salary_2023["Year"] = 2023

city_salary_2023

             City  Area_Code Median_Annual_Salary  Year
35     Manchester  E08000003                33458  2023
141    Birmingham  E08000025                28648  2023
206       London   E12000007                38943  2023

In [12]:
from pathlib import Path

ons_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\raw\ons"
)

for p in ons_path.rglob("*"):
    name = p.name.lower()
    if ("local" in name or "ashe" in name) and (
        "2024" in name or "2025" in name
    ):
        print(p)

D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Occupation_2024
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Occupation_2025
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Region_Occupation_2024
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Region_Occupation_2025
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Region_Occupation_2025\ashetable152025provisional
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Region_Occupation_2025\ashetable152025provisional\ASHE Table 15 (3) 2025 Provisional
D:\MScProjects\labour-market-intelligence\data\raw\ons\ONS_ASHE_Region_Occupation_2025\ashetable152025provisional\ASHE Table 15 (4) 2025 Provisional

In [15]:
from pathlib import Path

ons_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\raw\ons"
)

for p in ons_path.iterdir():
    if "Local_Authority" in p.name:
        print(repr(p.name))

'ONS_ASHE_Local_Authority 2023.zip'
'ONS_ASHE_Local_Authority 2024.zip'
'ONS_ASHE_Local_Authority 2025.zip'

In [16]:
from pathlib import Path
import zipfile

ons_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\raw\ons"
)

for year in [2024, 2025]:
    zip_path = ons_path / f"ONS_ASHE_Local_Authority {year}.zip"

    print(f"\n--- {year} ---")

    with zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if "7.7a" in name.lower() or "annual pay" in name.lower():
                print(name)

--- 2024 ---
Work Geography Table 7.7a   Annual pay - Gross 2024.xlsx
Work Geography Table 7.7b   Annual pay - Gross 2024 CV.xlsx
Work Geography Table 7.8a   Annual pay - Incentive 2024.xlsx
Work Geography Table 7.8b   Annual pay - Incentive 2024 CV.xlsx

--- 2025 ---
PROV - Work Geography Table 7.7a   Annual pay - Gross 2025.xlsx
PROV - Work Geography Table 7.7b   Annual pay - Gross 2025 CV.xlsx
PROV - Work Geography Table 7.8a   Annual pay - Incentive 2025.xlsx
PROV - Work Geography Table 7.8b   Annual pay - Incentive 2025 CV.xlsx

In [17]:
import pandas as pd
import zipfile
from io import BytesIO

ons_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\raw\ons"
)

files = {
    2024: "Work Geography Table 7.7a   Annual pay - Gross 2024.xlsx",
    2025: "PROV - Work Geography Table 7.7a   Annual pay - Gross 2025.xlsx"
}

city_raw = {}

for year, filename in files.items():

    zip_path = ons_path / f"ONS_ASHE_Local_Authority {year}.zip"

    with zipfile.ZipFile(zip_path, "r") as z:
        excel_bytes = z.read(filename)

    city_raw[year] = pd.read_excel(
        BytesIO(excel_bytes),
        sheet_name="All",
        header=None
    )

    print(year, city_raw[year].shape)

2024 (406, 20)
2025 (406, 20)

In [18]:
city_codes = {
    "London": "E12000007",
    "Manchester": "E08000003",
    "Birmingham": "E08000025"
}

city_tables = []

# Add the 2023 table we already created
city_tables.append(city_salary_2023)

# Extract 2024 and 2025
for year in [2024, 2025]:
    df = city_raw[year]

    selected = df[
        df[1].isin(city_codes.values())
    ][[0, 1, 3]].copy()

    selected.columns = [
        "City",
        "Area_Code",
        "Median_Annual_Salary"
    ]

    selected["Year"] = year

    city_tables.append(selected)

# Combine all three years
city_salary = pd.concat(
    city_tables,
    ignore_index=True
)

city_salary = city_salary.sort_values(
    ["City", "Year"]
).reset_index(drop=True)

city_salary

           City  Area_Code Median_Annual_Salary  Year
0    Birmingham  E08000025                28648  2023
1    Birmingham  E08000025                32133  2024
2    Birmingham  E08000025                33374  2025
3    Manchester  E08000003                33458  2023
4    Manchester  E08000003                33272  2024
5    Manchester  E08000003                36554  2025
6       London   E12000007                38943  2023
7       London   E12000007                41586  2024
8       London   E12000007                43190  2025

In [20]:
# Make sure Year is the same datatype everywhere
city_salary["Year"] = pd.to_numeric(
    city_salary["Year"],
    errors="coerce"
).astype(int)

# Create Birmingham baseline
baseline = (
    city_salary.loc[
        city_salary["City"].str.strip() == "Birmingham",
        ["Year", "Median_Annual_Salary"]
    ]
    .copy()
    .rename(columns={
        "Median_Annual_Salary": "Birmingham_Baseline"
    })
)

print("Baseline:")
print(baseline)

# Merge
city_salary = city_salary.drop(
    columns=[
        "Birmingham_Baseline",
        "Salary_Premium_GBP",
        "Salary_Premium_Pct"
    ],
    errors="ignore"
)

city_salary = city_salary.merge(
    baseline,
    on="Year",
    how="left"
)

# Calculate premiums
city_salary["Salary_Premium_GBP"] = (
    city_salary["Median_Annual_Salary"]
    - city_salary["Birmingham_Baseline"]
)

city_salary["Salary_Premium_Pct"] = (
    city_salary["Salary_Premium_GBP"]
    / city_salary["Birmingham_Baseline"]
    * 100
).round(2)

city_salary

Baseline:
   Year Birmingham_Baseline
0  2023               28648
1  2024               32133
2  2025               33374

,City,Area_Code,Median_Annual_Salary,Year,Birmingham_Baseline,Salary_Premium_GBP,Salary_Premium_Pct
0,Birmingham,E08000025,28648,2023,28648,0,0.0
1,Birmingham,E08000025,32133,2024,32133,0,0.0
2,Birmingham,E08000025,33374,2025,33374,0,0.0
3,Manchester,E08000003,33458,2023,28648,4810,16.79
4,Manchester,E08000003,33272,2024,32133,1139,3.54
5,Manchester,E08000003,36554,2025,33374,3180,9.53
6,London,E12000007,38943,2023,28648,10295,35.94
7,London,E12000007,41586,2024,32133,9453,29.42
8,London,E12000007,43190,2025,33374,9816,29.41

In [21]:
from pathlib import Path

output_path = Path(
    r"D:\MScProjects\labour-market-intelligence\data\processed\city_salary_2023_2025.csv"
)

city_salary.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)
print("Shape:", city_salary.shape)

Saved: D:\MScProjects\labour-market-intelligence\data\processed\city_salary_2023_2025.csv
Shape: (9, 7)